
animal = input("Enter a name of an animal: ") 
plural_verb = input("Enter a plural verb: ")
random_name = input("Enter a random name: ")

print()
print("One day in the woods a " + animal + " saw a two legged being")
print()
print("with tremendous curiosity the " + animal + " started to get closer and closer")
print()
print("the " + animal + " became more and more curious and wanted to act in a shameless way")
print()
print(random_name + " decided to take a leisulerly walk through the forest just to get some time to himself")
print()
print("he suddenly saw a " + animal + " rushing toward him")
print()
print("At this point it was too late for " + random_name + " to do anything because the second the " + animal + " got to " + random_name + " the " + animal + " was already " + plural_verb + " " + random_name)
print()
print("The end!")
print()
print("Now fuck off!")
print()